siteTitle = "Peaches, Passion, and Programming."
siteDescr = "A blog by Kunal Shah."
siteAuthor = "Kunal Shah"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/kunalsh22"
siteGithubUrl = "https://github.com/kunalgorithm/"
siteEmailUrl = "kshah239@gmail.com"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"
